#!/bin/sh
# Switch your TV on and make it source the computer.
#
# Note: this doesn't work out-of-the-box on most hardware. You probably need
# a specially constructed DisplayPort-HDMI adapter, e.g. P/N 2JA63AA from HP.
# Connect the DP end to the DP port on your GPU, then use a normal HDMI cable
# to connect the HDMI end to your TV. Don't use the HDMI port on your GPU.
#
# See https://wiki.archlinux.org/title/HDMI-CEC#Hardware_setup
# and https://docs.kernel.org/admin-guide/media/cec.html#displayport-to-hdmi-adapters-with-working-cec
# for details.
#
# Tested by author with P/N 2JA63AA, Radeon RX 7800 XT GPU, and HiSense TV.
set -e

dev="${1:-0}"
cec_ctl() {
  cec-ctl -d"$dev" "$@"
}

my_edid() {
  wc -c /sys/class/drm/*/edid   | grep -v ^0 | grep -v 'total$' | head -n1 | cut '-d ' -f2
}

my_addr() {
  cec_ctl | sed -ne 's/^\s*Physical Address\s*:\s*//igp'
}

extract_types() {
  sed -ne 's/^\s*Primary Device Type\s*:\s*//igp'
}

# opportunistically run method 0 for speed
if [ -x /etc/les/hard-on ]; then
  /etc/les/hard-on 0 || true
fi

# configure cec on this computer and detect TV
# we do this at the same time, because if the TV is not detected then to fix it
# we have to retry configuration, not simply wait and retry detection
ov=
for act in a a a a b b b b c c c c x; do
  if cec_ctl -s --playback --osd-name="$(hostname)" --phys-addr-from-edid "$(my_edid)" -S | extract_types | grep -iq "tv"; then
    break;
  fi
  case "${ov}${act}" in
  a*)
    sleep 0.5
    ;;
  b*)
    if [ -x /etc/les/hard-on ]; then
      echo >&2 "TV not on HDMI-CEC. Executing hard-on script (method 1)."
      if /etc/les/hard-on 1; then ov=x; fi
    fi
    sleep 0.5
    ;;
  c*)
    if [ -x /etc/les/hard-on ]; then
      echo >&2 "TV not on HDMI-CEC. Executing hard-on script (method 2)."
      if /etc/les/hard-on 2; then ov=x; fi
    fi
    sleep 0.5
    ;;
  x*)
    if [ -x /etc/les/hard-on ]; then
      echo >&2 "TV still not confirmed on after several retries. Aborting. Sorry."
    else
      cat >&2 <<-EOF
Failed to detect a TV after 10 seconds. If everything was working before, for
example immediately after putting the TV on standby, it's possible that now
your TV is in a hard power-off state where even HDMI-CEC is off. In this case,
it's impossible for anything to control the TV - you'll have to switch it on
manually the normal way. You can also try reporting this to the manufacturer,
and ask them to keep HDMI-CEC on even in the hard power-off state.

You can also try adding a hard-on script to ~/.config/cec-autostart/hard-on
for example, that switches your TV on using an IR transmitter attached to your
computer, via "irsend" from the "lirc" package.
EOF
    fi
    exit 1
    ;;
  esac
done
echo >&2 "CEC configured and TV detected"

# switch the TV on
cec_ctl -s -t0 --image-view-on
echo >&2 "TV switching on..."

# wait for the TV to be on
while ! cec_ctl -s -t0 --give-device-power-status | grep -i 'pwr-state: *on'; do
  sleep 0.5
done
echo >&2 "TV should be switched on by now"

# switch the TV screen to this computer, as opposed to some other device
cec_ctl -s -t0 --active-source phys-addr="$(my_addr)"
# last step so don't bother with detection of success
